In [4]:
import pandas as pd
import statsmodels.formula.api as smf
import matplotlib.pyplot as plt
import numpy as np
df=pd.read_csv("binary.csv")
print(df.head())

   admit  gre   gpa  rank
0      0  380  3.61     3
1      1  660  3.67     3
2      1  800  4.00     1
3      1  640  3.19     4
4      0  520  2.93     4


In [8]:
df.columns = ["admit","gre","gpa","prestige"]
print(df.columns)

Index(['admit', 'gre', 'gpa', 'prestige'], dtype='object')


In [9]:
print(df.describe())

            admit         gre         gpa   prestige
count  400.000000  400.000000  400.000000  400.00000
mean     0.317500  587.700000    3.389900    2.48500
std      0.466087  115.516536    0.380567    0.94446
min      0.000000  220.000000    2.260000    1.00000
25%      0.000000  520.000000    3.130000    2.00000
50%      0.000000  580.000000    3.395000    2.00000
75%      1.000000  660.000000    3.670000    3.00000
max      1.000000  800.000000    4.000000    4.00000


In [11]:
print(df.prestige.unique())

[3 1 4 2]


In [20]:
dummy_ranks=pd.get_dummies(df['prestige'],prefix="prestige")
print(type(dummy_ranks))
dummy_ranks

<class 'pandas.core.frame.DataFrame'>


prestige_1  prestige_2  prestige_3  prestige_4
0             0           0           1           0
1             0           0           1           0
2             1           0           0           0
3             0           0           0           1
4             0           0           0           1
5             0           1           0           0
6             1           0           0           0
7             0           1           0           0
8             0           0           1           0
9             0           1           0           0
10            0           0           0           1
11            1           0           0           0
12            1           0           0           0
13            0           1           0           0
14            1           0           0           0
15            0           0           1           0
16            0           0           0           1
17            0           0           1           0
18            0           1           0           0
19            1           0           0           0
20            0           0           1           0
21            0           1           0           0
22            0           0           0           1
23            0           0           0           1
24            0           1           0           0
25            1           0           0           0
26            1           0           0           0
27            0           0           0           1
28            0           1           0           0
29            1           0           0           0
..          ...         ...         ...         ...
370           0           1           0           0
371           0           0           1           0
372           1           0           0           0
373           1           0           0           0
374           0           1           0           0
375           0           0           0           1
376           0           1           0           0
377           0           1           0           0
378           0           0           1           0
379           0           1           0           0
380           0           1           0           0
381           0           1           0           0
382           0           1           0           0
383           1           0           0           0
384           0           1           0           0
385           1           0           0           0
386           0           1           0           0
387           0           1           0           0
388           0           1           0           0
389           0           1           0           0
390           0           1           0           0
391           0           1           0           0
392           0           0           1           0
393           0           1           0           0
394           0           0           1           0
395           0           1           0           0
396           0           0           1           0
397           0           1           0           0
398           0           1           0           0
399           0           0           1           0

[400 rows x 4 columns]

In [22]:
cols_to_keep=['admit','gre','gpa']
data=df[cols_to_keep].join(dummy_ranks.loc[:,'prestige_2':])
data.head()

admit  gre   gpa  prestige_2  prestige_3  prestige_4
0      0  380  3.61           0           1           0
1      1  660  3.67           0           1           0
2      1  800  4.00           0           0           0
3      1  640  3.19           0           0           1
4      0  520  2.93           0           0           1

In [54]:
data_tr=data.loc[0:250]
data_ta=data.loc[251:]
train_cols= data.columns[1:]
logit= smf.Logit(data_tr['admit'],data_tr[train_cols])
result=logit.fit()          

Optimization terminated successfully.
         Current function value: 0.531556
         Iterations 6


In [32]:
print(result.params)
print(result.summary())

gre           0.003046
gpa          -0.373806
prestige_2   -1.255927
prestige_3   -2.067083
prestige_4   -2.602064
dtype: float64
                           Logit Regression Results                           
Dep. Variable:                  admit   No. Observations:                  251
Model:                          Logit   Df Residuals:                      246
Method:                           MLE   Df Model:                            4
Date:                Fri, 05 Jan 2018   Pseudo R-squ.:                  0.1199
Time:                        13:48:25   Log-Likelihood:                -132.39
converged:                       True   LL-Null:                       -150.43
                                        LLR p-value:                 2.792e-07
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
gre            0.0030      0.001      2.124      0.034       0.000       0.006
g

In [41]:
result.conf_int()#bujhini

0         1
gre  0.000399  0.005483
gpa -1.231656 -0.311645

In [48]:
cols_to_keep=['admit','gre']
data=df[cols_to_keep].join(dummy_ranks.loc[:,'prestige_2':])
data.head()
train_cols= data.columns[1:]
logit= smf.Logit(data_tr['admit'],data_tr[train_cols])
result=logit.fit()

Optimization terminated successfully.
         Current function value: 0.531556
         Iterations 6


In [49]:
print(result.params)
print(result.summary())

gre           0.001150
prestige_2   -1.349631
prestige_3   -2.216217
prestige_4   -2.734433
dtype: float64
                           Logit Regression Results                           
Dep. Variable:                  admit   No. Observations:                  251
Model:                          Logit   Df Residuals:                      247
Method:                           MLE   Df Model:                            3
Date:                Fri, 05 Jan 2018   Pseudo R-squ.:                  0.1131
Time:                        14:02:39   Log-Likelihood:                -133.42
converged:                       True   LL-Null:                       -150.43
                                        LLR p-value:                 1.970e-07
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
gre            0.0012      0.001      2.240      0.025       0.000       0.002
prestige_2    -1.3496   

In [52]:
result.pred_table()

array([[ 163.,   16.],
       [  49.,   23.]])

In [55]:
data_ta.head()

admit  gre  prestige_2  prestige_3  prestige_4
251      0  620           0           0           1
252      1  520           1           0           0
253      1  540           0           0           1
254      1  740           0           0           1
255      0  640           0           1           0

In [57]:
data_ta['predition']=result.predict(data_ta[train_cols])
data_ta.head()

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


admit  gre  prestige_2  prestige_3  prestige_4  predition
251      0  620           0           0           1   0.116999
252      1  520           1           0           0   0.320515
253      1  540           0           0           1   0.107820
254      1  740           0           0           1   0.132032
255      0  640           0           1           0   0.185436

In [60]:
data_ta['admit_pred']=data_ta['predition']>0.5
data_ta

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


admit  gre  prestige_2  prestige_3  prestige_4  predition  admit_pred
251      0  620           0           0           1   0.116999       False
252      1  520           1           0           0   0.320515       False
253      1  540           0           0           1   0.107820       False
254      1  740           0           0           1   0.132032       False
255      0  640           0           1           0   0.185436       False
256      1  520           1           0           0   0.320515       False
257      1  620           0           1           0   0.181986       False
258      0  520           1           0           0   0.320515       False
259      0  640           1           0           0   0.351294       False
260      0  680           1           0           0   0.361851       False
261      0  440           1           0           0   0.300811       False
262      1  520           0           1           0   0.165482       False
263      1  620           0           1           0   0.181986       False
264      1  520           0           1           0   0.165482       False
265      0  380           0           1           0   0.144420       False
266      0  560           0           0           1   0.110054       False
267      1  600           0           1           0   0.178586       False
268      1  680           1           0           0   0.361851       False
269      0  500           0           1           0   0.162329       False
270      1  640           1           0           0   0.351294       False
271      0  540           0           1           0   0.168684       False
272      1  680           1           0           0   0.361851       False
273      0  660           0           0           0   0.681199        True
274      0  520           1           0           0   0.320515       False
275      1  600           1           0           0   0.340881       False
276      0  460           0           1           0   0.156168       False
277      1  580           0           0           0   0.660887        True
278      1  680           0           0           1   0.124320       False
279      1  660           1           0           0   0.356555       False
280      0  660           1           0           0   0.356555       False
..     ...  ...         ...         ...         ...        ...         ...
370      1  540           1           0           0   0.325546       False
371      1  680           0           1           0   0.192488       False
372      1  680           0           0           0   0.686174        True
373      1  620           0           0           0   0.671123        True
374      0  560           1           0           0   0.330618       False
375      0  560           0           0           1   0.110054       False
376      0  620           1           0           0   0.346069       False
377      1  800           1           0           0   0.394297       False
378      0  640           0           1           0   0.185436       False
379      0  540           1           0           0   0.325546       False
380      0  700           1           0           0   0.367181       False
381      1  540           1           0           0   0.325546       False
382      0  540           1           0           0   0.325546       False
383      0  660           0           0           0   0.681199        True
384      1  480           1           0           0   0.310577       False
385      0  420           0           0           0   0.618499        True
386      1  740           1           0           0   0.377938       False
387      0  580           1           0           0   0.335730       False
388      0  640           1           0           0   0.351294       False
389      0  640           1           0           0   0.351294       False
390      1  800           1           0           0   0.394297       False
391      1  660           1   

In [63]:
pred=np.array(data_ta['admit_pred'])
table=np.histogram2d(data_ta['admit'],pred,bins=2)[0]
table

array([[ 82.,  12.],
       [ 45.,  10.]])